### ISSUE TITLE
[Feature request] DLSS Tweaks Support

### ISSUE THREAD

**Issue by adamcirillo** [beeradmoore/dlss-swapper#122]
are you able to add support for DLSS Tweaks to add DLAA to games? link to github https://github.com/emoose/DLSSTweaks

**Comment by beeradmoore** [comment]
Giving it a quick look over of how it works it may not fit nicely into the flow of DLSS Swapper. Looks like DLSS Tweaks dll needs to be added into the path of the exe file, and in some cases itself needs be renamed in order to work for some games.

If placing it in the same path as DLSS dll would make it load or if there was other ways to make it more automated then it could be something that I could talk to @emoose about to see if they are comfortable with it being added.

**Comment by beeradmoore** [comment]
Closing this issue for now. If this opportunity ever comes up again I am more than happy to re-open.
