### ISSUE TITLE
[Feature request] Link to DLSS release notes from the library

### ISSUE THREAD

**Issue by revlisoft** [beeradmoore/dlss-swapper#127]
**Is your feature request related to a problem? Please describe.**
Show release notes of various DLSS libraries

**Describe the solution you'd like**
Would be nice to link or mouse over the various DLSS versions to show the release notes from https://github.com/NVIDIA/DLSS/releases or some other area.

**Additional context**
Helps decides which version to use for the various games installed

**Comment by beeradmoore** [comment]
That is a possibility and it would fit nicely in the context of "game notes" feature to be added. However the release notes listed from nVidia are not end user release notes and I think the only thing of value is:
- Performance and Optimization fixes
- Bug Fixes & Stability Improvements
Which at this point I don't think is handy. Is there anything specific in the other release notes that people may want to see?

**Comment by revlisoft** [comment]
ahh.. that's true.  If it's mostly that the not as useful.  Maybe links to reddit where folks post their experiences with the new DLLs?

https://www.reddit.com/r/nvidia/search/?q=dlss%20dll&restrict_sr=1&sr_nsfw=

**Comment by beeradmoore** [comment]
It's difficult because we are not linking them to anything specific so who knows what may come up when they go there tomorrow. Even if the search included 3.1.1 in the query string it might not give great results. We have had similar issues in the past trying to let users rate what DLSS versions work how well on what game. It can vary depending on hardware, game version installed, drivers, etc (and in that case, would require external database to keep track of things, probably a user system to not let anyone submit anything anonymously).

We do have our own place to discuss swapping DLSS dlls in general and not nVidia as a whole, but we already link to [that](https://www.reddit.com/r/DLSS_Swapper/). Can lead a horse to water, etc etc :P
