### ISSUE TITLE
[Feature request] Multiple Game File Paths

### ISSUE THREAD

**Issue by MS2620** [beeradmoore/dlss-swapper#131]
**Is your feature request related to a problem? Please describe.**
It would be nice if we could select the folders where the games are installed. This would allow the user to only select certain paths allowing them to also choose specific games in different paths.

**Describe the solution you'd like**
I would like for there to be a add path button on the games section, nothing too over the top or complicated.

**Comment by beeradmoore** [comment]
Hey @MauroSousa-08013495 , I get what you mean of why you would want this, but unfortunately that isn't how DLSS Swapper loads games. And TBH am unsure how GeForce Experience does a similar thing.

DLSS Swapper will look at your game library (eg. Steam) config files to see where games are stored. Those config files also include additional data about the game title, game ID, game thumbnail image, etc. If we point to a folder of many games we no longer have any that. Plus we would need to ensure what we are talking about with a folder, like are the games directly inside this folder? eg. What happens if a user selects C drive because all their games are installed on C drive, do they now have games show up called "Program Files" and "Users".

BUUUUUT there is long overdue feature requested in #8 which may help with what you are after. It allows adding a single game folder, but then the user is required to manually enter the game name (we estimate this by pre-filling folder name as game name) and then optoinally provide a thumbnail image to keep UI consistent.
