### ISSUE TITLE
[Feature request] Add the ability to update frame generation dll

### ISSUE THREAD

**Issue by Dicehunter** [beeradmoore/dlss-swapper#156]
**Is your feature request related to a problem? Please describe.**
No issue just a feature request.

**Describe the solution you'd like**
Would be great if we could also have the option of updating frame generation dll's. 

**Additional context**
None needed.

**Comment by beeradmoore** [comment]
Hey Dicehunter, 
Thanks for the the report. This issue is currently being tracked in #85, work has started on adding this in. The work to do this also opens the door to add FSR and XeSS support as well.

Closing this issue as a duplicate for now. If you want to be updated of progress, please go to #85 and hit subscribe on the right hand side.

**Comment by Dicehunter** [comment]
> Hey Dicehunter, Thanks for the the report. This issue is currently being tracked in #85, work has started on adding this in. The work to do this also opens the door to add FSR and XeSS support as well.
> 
> Closing this issue as a duplicate for now. If you want to be updated of progress, please go to #85 and hit subscribe on the right hand side.

Appreciate the reply and thanks for the info :)
