### ISSUE TITLE
[BUG] Installer flagged as malicious by hybrid analysis and virustotal

### ISSUE THREAD

**Issue by syberphunk** [beeradmoore/dlss-swapper#160]
**Describe the bug**
Virustotal and hybrid-analysis.com report the installer as malicious
https://www.virustotal.com/gui/file/4ba4dd30e5aecc3ea65297631744a17888a2d11ce005ecba473febfc47d149ea
https://www.hybrid-analysis.com/sample/4ba4dd30e5aecc3ea65297631744a17888a2d11ce005ecba473febfc47d149ea

**To Reproduce**
- Download DLSS installer executable
- Upload to virustotal / hybrid-analysis
- See that it's marked as malicious and question how trustworthy it is, even if it's a false positive

**Expected behavior**
I expect it to report the file as clean.

**Screenshots**
![image](https://github.com/beeradmoore/dlss-swapper/assets/234857/de6a877c-6dbd-4d38-a6fd-0bfd964ca21f)
![image](https://github.com/beeradmoore/dlss-swapper/assets/234857/6a1fad91-b72b-4539-855e-b132cffd6058)
![image](https://github.com/beeradmoore/dlss-swapper/assets/234857/c2e6e36e-de4c-49e1-83a2-ea1524c99303)
![image](https://github.com/beeradmoore/dlss-swapper/assets/234857/b5fb4e1b-733a-4e7d-b407-7653975faf09)

**Additional context**

**Comment by beeradmoore** [comment]
Yeah, that is somewhat unfortunate. 

Without stripping things out of the all and running small tests piece by piece we couldn't narrow down what it is. From initial report it looks like it's that the method we use to download DLSS files is being marked as false positive. 

We can't really change that in order to make AV happy, we may need to submit the files as clean and hope for the best.

Do you have any other suggestions?
