### ISSUE TITLE
[Feature request] EA Game Launcher Games Support

### ISSUE THREAD

**Issue by MiLeX84** [beeradmoore/dlss-swapper#193]
**Is your feature request related to a problem? Please describe.**
Please add support for EA Game Launcher Games, they are located in a different location and the EA launched is currently not listed as a source like Steam, GOG, Epic Game Store etc.

**Comment by beeradmoore** [comment]
Hey @MiLeX84 , this issue is being tracked in #68 so I'll close this one as a duplicate. If you want to get updates go to that issue and hit subscribe on the right hand side.

As for progress, last I checked we weren't able get a list of games loading in DLSS Swapper. If we can't get that to work at all you will have to wait for DLSS Swapper v1.1 when you can manually add a game by its folder.
