### ISSUE TITLE
No persistence of records

### ISSUE THREAD

**Issue by Spook12134567890** [beeradmoore/dlss-swapper#204]
I have over 1,000 games installed via Steam. It takes 20 minutes for this program to scan them. If I then click away from the Games tab (to Library for example to download a DLSS version) when I return to the Games tab it starts the scan again. It is not practical to use the program at all. It needs to remember the games/locations and just throw an error if ithe game is not found when swapping DLSS versions. Refreshing the tab should only be allowed manually (and an automatic option on a timer maybe). The games tab should be persistent between launches of the program.

In addition the program should have a built in option to revert any changes that have been made and set a game back to the original version.

Other than this fantastic tool!

**Comment by beeradmoore** [comment]
Hey @Spook12134567890, I have some good news for you!

First up, the restoring of DLSS files should be an option that exists already. We only keep track of this based on copying the original file and appending .dlss to the file name. If the game updates itself it's hard for us to know if that has happened and if we should then delete the .dlss file.

The latest update has a few things that will be helpful to you:
- moved game store in memory to somewhere else so it isn't wiped by navigating (in theory this shouldn't be happening currently but I think that's bugged)
- game cache so initial load will be much much faster. This cache could also be used for monitoring what DLSS version has been swapped vs what is on disk.
- game cover thumbnail resizing and caching. No need to load 1080p images to display them at 200x300. Also they are saved to disk so it isn't fetched online on every launch.
- improved loading from background threads. Need to balance this with IO performance so not to use all the seek performance at once. In future this could be adjusted to make sure we don't hammer a single disk so much.

**Comment by Rool-IO** [comment]
Hey @beeradmoore , just bumping on your answer regarding the file extension change :
When you mention it, everywhere you write it's changed to .dlss but it's actually always been renamed to .dlsss (3 s instead of 2).
It's really not a problem but I thought you might want to change that behavior in future versions to properly have it match what you tell/explain to users ;)

**Comment by beeradmoore** [comment]
Thanks, it's not the program that is broken, just what I tell people is the wrong thing 😂

But changing it in the program will likely make me right in the future 🤔

**Comment by ColonelGerdauf** [comment]
Speaking of read speed, Everything Search also does a stellar job of fetching file paths quickly. It uses an algorithm that is more efficient than what Windows uses. One of the things it does that makes it near-instant in practical use, is that it stores a directory index so that it can look up the index rather than the drive again. This index can handle delta updates fairly well.

I wonder if DLSS Swapper can use its own version of this mechanism.

**Comment by beeradmoore** [comment]
I just looked up Everything Search, it does the same MFT as WizTree does mentioned above.

I had prototyped some sample code a while back, and I'd love to look into it for a post v1.1 update.

That also looks like a useful tool, thanks for sharing.
