### ISSUE TITLE
[BUG] DLSS 3.6.0 is not available in program

### ISSUE THREAD

**Issue by Nypheena** [beeradmoore/dlss-swapper#209]
DLSS 3.6.0 has been released but it is not in DLSS swapper, why?

**Comment by DERDAR921** [comment]
yea its been 2 days i think

**Comment by beeradmoore** [comment]
Hey all, 
Sorry about that. I posted [on Twitter](https://twitter.com/dlss_swapper/status/1770976133917659584) about 30 hours ago that it was delayed, but I guess I need more places to reach more people. Would cross posting to reddit have helped?

 It is fixed as of about 2 hours ago.

Problem was I have a different tool that checks DLSS dlls to make sure they are signed by nVidia (would be a shame if I distributed a virus to you all 😅) but it was not playing ball. This has since been resolved and should not pose a problem in the future.

If you want to read more about the problem was and the fix, you can see that [here](https://github.com/beeradmoore/dlss-archive/issues/9#issuecomment-2016352030).

In future if you are annoyed that a DLSS version has not been added you can always add it manually via the DLSS library page.

I did have plans to make DLSS Swapper update DLSS files directly from the DLSS SDK repository run by NVIDIA rather than my own archive, but if you go digging you'll find that they haven't even posted it. So I guess that plan is off the table if they are not going to release their own updates in their own update channel and we are instead back to the old (current) system.

**Comment by beeradmoore** [comment]
All good :)

If there are issues like this in the future I'll try post (and pin) them here to help get the info out.
