### ISSUE TITLE
[Feature request] Some games crash depending on the DLSS versions swapped

### ISSUE THREAD

**Issue by KitKattx** [beeradmoore/dlss-swapper#234]
**Is your feature request related to a problem? Please describe.**
Some games crash depending on the DLSS versions swapped

**Describe the solution you'd like**
It would be nice to have a list of supported DLSS versions for different games that people could have the option to add on to so we can avoid crashes

**Additional context**
Should also show if a game or DLSS version hasn't been checked

**Comment by beeradmoore** [comment]
This issue you mentioned popped up recently with #232, but has been discussed in various ways for some time.

The short answer is, it's out of scope of the project.

The long answer is, to be able to monitor what works and what doesn't we would need to ask users constantly if the version of DLSS they swapped works or not. Then after that we would need a web server and database to store their answers. We would also need to deal with what happens if 2 users say conflicting things, what if the game updates and now crashes or doesn't crash. So we would likely also need to monitor game versions.

On top of this we can't have open endpoints allowing users to submit data, the internet is terrible and people will abuse this system with bots. So then we'd need to have a login system to ensure that only real people can access it. But now on top of that we would need to start sending emails for password resets, email confirmations, etc. But now the bots would get smarter and I am playing cat and mouse trying to prevent system abuse.

It is all very possible to do and is actually a lot more aligned to what I do in day to day work than DLSS Swapper itself 😅. However it is a lot of time and (my) money spent building, running, and maintaining that system. I'd rather spend that time adding new features to DLSS Swapper itself.



While it isn't what you wanted, the next version of DLSS Swapper does have a notes section where you can add notes per game. These notes only exist on your system but it is a useful place to remind yourself that you got crashing with DLSS version x.y.z.

**Comment by Eduxki** [comment]
dumb dumb dumb dumb dumb dumb, people buy 20 hundred bucks gpus because yes, dlss wowowwowowowowowowowwow

**Comment by KitKattx** [comment]
> This issue you mentioned popped up recently with #232, but has been discussed in various ways for some time.
> 
> The short answer is, it's out of scope of the project.
> 
> The long answer is, to be able to monitor what works and what doesn't we would need to ask users constantly if the version of DLSS they swapped works or not. Then after that we would need a web server and database to store their answers. We would also need to deal with what happens if 2 users say conflicting things, what if the game updates and now crashes or doesn't crash. So we would likely also need to monitor game versions.
> 
> On top of this we can't have open endpoints allowing users to submit data, the internet is terrible and people will abuse this system with bots. So then we'd need to have a login system to ensure that only real people can access it. But now on top of that we would need to start sending emails for password resets, email confirmations, etc. But now the bots would get smarter and I am playing cat and mouse trying to prevent system abuse.
> 
> It is all very possible to do and is actually a lot more aligned to what I do in day to day work than DLSS Swapper itself 😅. However it is a lot of time and (my) money spent building, running, and maintaining that system. I'd rather spend that time adding new features to DLSS Swapper itself.
> 
> While it isn't what you wanted, the next version of DLSS Swapper does have a notes section where you can add notes per game. These notes only exist on your system but it is a useful place to remind yourself that you got crashing with DLSS version x.y.z.

I see, it's just a hassle to remember which files work for what. I appreciate the response though!

**Comment by beeradmoore** [comment]
Thanks for understanding
