### ISSUE TITLE
[Feature request] Compatibility list in README / wiki

### ISSUE THREAD

**Issue by satvikpendem** [beeradmoore/dlss-swapper#64]
**Is your feature request related to a problem? Please describe.**
It would be cool to know the current compatibility of various games and what version works best for them.

**Describe the solution you'd like**
A compatibility list in the README or via a wiki would work best I believe. You as the creator wouldn't have to maintain it if it were in a wiki, you could allow people to edit it freely and people would be able to update the wiki with their experiences of what DLSS version works best.

**Additional context**
NA

**Comment by beeradmoore** [comment]
Hey @satvikpendem. Yeah this has been discussed a few times, it would be very nice but at the same time its difficult. 

The idea of a wiki is a newly suggested one, but ultimately I (or someone else) would have to still moderate it. It also needs to be hosted somewhere, are wikis free? This repo can have a wiki, and I'd be fine either taking pull requests or new issues to update it. I could add a new issue template for reporting game compatibility. 

As far as I know with the later versions of DLSS they are compatible everywhere, and ideally people should be using the latest everywhere (it was a little all over the shop in earlier versions). One of the bigger issues is that 1.x DLSS is not compatible with 2.x and vice versa. I think (but haven't tested) a game with 2.0 DLSS can run fine with 2.3 DLSS. I think @MorGuux had suggested making the DLSS selection box only show 1.x for 1.x compatible game (game already had 1.x in it) and 2.x for 2.x games. If all games are indeed compatible then we wouldn't need a compatibility list.

I think a nice solution would be if DLSS swapper could occasionally prompt people to report if they were happy with DLSS 2.3.2 in game X after it knows they had played it 3 times. But that is then infringing on their privacy, and then the endpoints where that data would get submitted to would need to be protected so people can't just spam fake data, etc. Thats when it gets complicated. This data could then also feed into the app. So you try select v2.3.2 for Metro EE and it could say that lately a large number of users have recommends v2.3.1, would you like to load that instead.

The other thing on all of this is compatibility list is somewhat subjective. It should all be compatible and the game should all run fine. But someone may say Metro EE is 100% compatible, but I'd disagree because the blaring around the gun sights is still awful. 

I am 100% on board for helping people get the most out of their game. So long as we can do it efficiently, usefully, and in a way that doens't get in peoples way.

**Comment by beeradmoore** [comment]
I just got this via Twitter.

> I'm using your DLSS Swapper tool for Outriders which has version 2.2.9. When I swap to version 2.3.4 the game has the DLSS option grayed out / not available. This is the case with version 2.2.18 as well. Resetting to default is fine. Any insight?

**Comment by satvikpendem** [comment]
Maybe we could make a page on the PC gaming wiki website so you wouldn't have to manage it directly but you could link people over there in order for them to edit the page.

**Comment by beeradmoore** [comment]
On our subreddit I've started a pinned [megathread for posting compatibility](https://www.reddit.com/r/DLSS_Swapper/comments/s3mbzh/game_compatibility_megathread/).

(Reason why this route is I think reddit will get more engagement than a github issue or wiki)
