### ISSUE TITLE
[Feature request] PE (portable) binaries

### ISSUE THREAD

**Issue by tamodolo** [beeradmoore/dlss-swapper#67]
**Is your feature request related to a problem? Please describe.**
The actual isn't portable.

**Describe the solution you'd like**
Move project to PE binaries. (.exe extension)

**Additional context**
Convenience.

**Comment by tamodolo** [comment]
Probably not. It's hard to sumarize why ms store is bad. For me it causes big problems with storage space so I just go download the exe version of anything I need instead. I think old habits never changes if the alternatives don't proves to be way better. Example: MS is trying to make me use the my documents since winxp by flooding file explorer with links to it and hiding the root devices. Over time the default folders for files windows offers proved to be very dangerous to use so I find quite annoying windows keeping trying to change how I use my PC. It's the same way with ms store: It's like there is a big warning signal in front of it telling me it's very dangerous to use.

I find the old method way better: copy the program folder indo a pendrive and that's it. No internet needed, no weird ms behavior. You run it and it'll work. I know it's a preference at most but I'll just keep using what is granted to work and not tied to something that can disapear tomorrow. winsdk is a deal breaker for me as I can't access or control it.

Besides my preferences, making this program as win32 binary is a convenience. The program is yours and is fair for you to do what you see most fit for it.

**Comment by beeradmoore** [comment]
Unfortunately making it portable adds new problems from the weird (eg. We used to store files in documents instead of appdata and some users somehow had permission issues here), to the unforeseen (like I mentioned earlier about the issue with dependencies)

Changing the app to be win32 isn't just flicking a config option in the app and will add a lot of refactoring.

It's a lot of work to give us the ability to have someone put DLSS Swapper on a USB stick so they can use it across multiple computers. I don't see this as being a major feature requested by users. But this issue will remain open for now so people can give it a 👍 to let us know if they would use it.

I think the way forwards is Windows Store as it gives a much more friendly user experience. I'll continue to publish builds (with auto updates disabled) on GitHub so you can manually grab the app installer. I'll also be looking at pushing builds to winget so people can install without having to deal with the store. Although neither of these solutions are portable nor will they just dump files in any old directory.

Maybe at some point of time allows (or if someone else wants to do it) we could use the same core engine and make "DLSS Swapper Lite" or "DLSS Swapper Portable" which doesn't bring along any of the flair and dependencies of the fully fledged version but still allows the basic functionality.

**Comment by inoperable** [comment]
Have you ever traced the M$ telemetry during a single M$ store installation - or better - any other M$ service interaction? 
Have you ever started Visual Studio with a TCP/IP monitor, like, say, Wireshark? I strongly advise to run it on your system, with all privacy settings at opt out and hacked with tools like wpd.app or blackbird, or so other promosing full privacy coverage, going so far as modifying the firewall rules to ban all m$ telemetry ips known, and yet it still manages to call home. Don't take my word on it - just run your system on idle and then take a peek at your log. 

Trivia: If you click WIN key it calls home (it does not matter if you opted out of web search or not) and this goes on and on and on. I don't want to rant - like I said - don't take my word on it - try to actively monitor your Windows on its TCP/IP behavior...

Their privacy policy is a joke, I don't necessarily want to feed the M$ yet again another data set about me through "few clicks" in the M$ Store. I give you a simple example: install newest powershell, opt out of telemetry, start using it, despite explicit opting out it still calls home and still sends data. I have a discussion with M$ on very github about that since hmmm 4+ years about finally adding an opt-out option to the setup.exe

M$ Store is the last thing i would call friendly experience (must log-in, must use M$ account and so on...) from my point of view, that is - which of course dont have to align with yours, sure, but maybe might be worth a consideration.

**Comment by inoperable** [comment]
![image](https://user-images.githubusercontent.com/1571074/169696237-e4c0ac70-adfc-4216-a05f-e16d4d4259bc.png)
I don't want to be ungrateful, but why put an msix here if I can't install it anyways?

**Comment by beeradmoore** [comment]
I believe I have already mentioned above why no portable edition.

Did you follow the [install instructions](https://beeradmoore.github.io/dlss-swapper/install/) in the readme for manual installation?

**Comment by inoperable** [comment]
I missed it (rtfm...), got it. I understand your argument, thanks for the work and effort, the rant might have been a bit misplaced :-)

**Comment by beeradmoore** [comment]
> I don't think they could make this program a portable .exe because of the way it's made.

This should now be possible now that unpackaged applications are possible with WindowsAppSDK apps. Just need time and motivation to do those extra steps. But when it is the app will be distributed as an installer and as a portable zip. No more certificates and those extra shenanigans.

**Comment by beeradmoore** [comment]
This should now be available with the [1.0 release](https://github.com/beeradmoore/dlss-swapper/releases/tag/v1.0.0.0). If you have any problems, please file an issue.
