### ISSUE TITLE
[BUG] documentation has contradictory information regarding auto update

### ISSUE THREAD

**Issue by magne4000** [beeradmoore/dlss-swapper#95]
**Describe the bug**
The doc has contradictory information https://beeradmoore.github.io/dlss-swapper/install/

In the _Recommended Install Instructions_ section:
> DLSS Swapper is now on the Windows Store! You can install builds directly from GitHub using the manual method below, **however they will not automatically update when a new version is available** (although they will tell you about it).

In the _Updating_ section:
> DLSS Swapper has an silent updater built in. If a new build is available it will be downloaded and installed in the background. The next time you launch the app you will have an updated build.

Which is it?

Also, Microsoft Store version is `9.9.0`, not sure why it's not up to date.

**Comment by beeradmoore** [comment]
There are lots of people who despise the Windows Store. They choose to download from GutHub instead (maybe they forget they are both MSFT companies?). Auto-updater exists because they won't be subbed to GitHub releases, nor following any of our socials for update announcements. When new things roll out at least they will get it. 

For less advanced users we recommend Windows Store so that way you don't need to download a certificate (which you need to unprompted to get a new one every year), and you don't need to know what specific file in the releases tab you should be getting. Hopefully the instructions help most people do this but there is still messages I get of people having trouble who don't even know that install page exists.

The Windows Store version being out of date is an issue I am dealing with the Windows Store at the moment. For some reason they suddenly said apps are not allowed to download executables as this bypasses the review process and is a security flaw. I appealed this (and in this time had also uploaded a second update) but they said remove the download functionality or remove the app from the store. So I am planning to do what they said, remove the download and just embed every DLSS version within the app 😂. I have not had time to do this yet as I need to shuffle some things to get this to work.

I wish to keep the Windows Store alive because it is much easier to direct people to and get them to install. Also means people can install/update with tools like winget and I don't need to do additional things to manage that.


So yep, Windows Store is preferred but it is currently out of date. If you only use Steam then there is nothing new in later versions. We are in the process of fixing the release.

In future we are looking at making DLSS Swapper what is called an unpackaged app which means we can then also make our own installer program. This removes the requirement for certificate and knowing what file to download from releases page. This makes GitHub installs much easier.

At that point I don't know what is the preferred install method. We will see 🤷‍♂️. I hope that answers your questions about why it's in shambles a little currently.

**Comment by magne4000** [comment]
😄 no wonder I was lost, thanks for the clear explanation!
Would the unpackaged version allow release through chocolatey? It's my go-to default if an app is on there.

**Comment by beeradmoore** [comment]
It should be possible to deploy through chocolatey. Ideally I'll have GitHub Actions building the app to distribute to Windows Store, GitHub Releases, Chocolatey, etc. That will make it easier to use the external systems if I don't have to touch anything myself.

I double checked the code and yeah, that updating notes were completely wrong. It will check for updates but it will not install them. I've updated it to the following to be more clear. Thanks for reporting that.

> If you installed via the Windows Store DLSS Swapper should update automatically.
>
> If you installed via GitHub you will be notified about a new update on launch. You can also manually check for updates in settings. Unlike the Windows Store version, DLSS Swapper from GitHub will not update automatically. If you are ever unsure you can always check the [releases section](https://github.com/beeradmoore/dlss-swapper/releases) in our Github repository.

**Comment by magne4000** [comment]
🙇
